"Mendefinisikan tipe data Branch sesuai kolom di database"
type Branch {
    id: ID!
    kode_cabang: String!
    nama_cabang: String!
    alamat: String!
    created_at: String
    updated_at: String
}

"--- READ DATA (Queries) ---"
type Query {
    branches: [Branch!]! @all

    branch(kode_cabang: String! @eq): Branch @find

    me: User @auth
}

"--- CREATE, UPDATE, DELETE (Mutations) ---"
type Mutation {
    createBranch(
        id: ID!
        kode_cabang: String!
        nama_cabang: String!
        alamat: String!
    ): Branch! @create

    updateBranch(
        id: ID!
        kode_cabang: String
        nama_cabang: String
        alamat: String
    ): Branch! @update

    "Hapus cabang berdasarkan KODE CABANG"
    deleteBranch(
        kode_cabang: String! @eq   # <-- Ganti id jadi kode_cabang di sini
    ): Branch @delete
}

type AuthPayload {
    token: String!
    user: User!
}

type Mutation {
    # Mutation untuk login dan generate token
    login(email: String!, password: String!): AuthPayload! @field(resolver: "App\\GraphQL\\Mutations\\Login")
}


type User {
    id: ID!
    name: String!
    email: String!
    
    role: String
    branch_id: Int
    
    email_verified_at: DateTime
    created_at: DateTime!
    updated_at: DateTime!
}
